---
# deploy production
# BINARYPATH=/home/wizard/code/fmpwizard/mrwilson ansible-playbook -i hosts/production playbooks/deploy.yml --ask-vault-pass -u root
# call
# ansible-playbook -i hosts/production playbooks/site-state.yml --ask-vault-pass --extra-vars "app_state=restarted" -u root
# to start the service

- hosts: serviceservers
  become: no
  gather_facts: no
  tags: ['full']
  vars:
    binaryPath: "{{ lookup('env', 'BINARYPATH')}}"
  tasks:
    - include: inc/app-copy-worker.yml

# stop serviceservers
- hosts: serviceservers
  tags: ['full']
  become: yes
  gather_facts: no
  tasks:
    - include: inc/app-state.yml app_state=stopped
