---

# ansible-playbook  init.yml -i hosts/production  --ask-vault-pass -u root

#To collect info like ip on server X to use on unit file for process Y
#- hosts: <some other host>
#  name: Gather facts from collectors
#  tasks: [ ]

- hosts: serviceservers
  become: no
  gather_facts: no
  vars:
    - envi: "{{ inventory_file | basename }}"
  vars_files:
    - "vars/{{ envi }}.yml"
    - "vars/{{ envi }}_vault.yml"
  roles:
    - init
